server:
  port: 9090

spring:
  application:
    name: bank
  datasource:
    url: jdbc:mysql://localhost:3307/bank_db
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: prod


management:
  endpoints:
    web:
      exposure:
        included: "*"
  endpoint:
    health:
      included: true
      probes:
        included: true

build:
  version: 3.0.0

bank:
  contactInfo:
    - "Raghuveer Reddy"
    - "Dev Engineer"
    - "rreddy@bank.com"
  onCallSupport:
    - (+91) 937452937
    - (+91) 253343556